name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run

    - name: Upload Cypress artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-artifacts
        path: |
          cypress/screenshots
          cypress/videos
